Cookies
ConduitPlatform/Conduit pull request #125
Opened 2022-04-20 13:03 UTC by sdimitris

Task #23dq8hb
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

If adding a **new feature**, the PR's description includes:
- Cookie functionality is configurable through `set_cookies.enabled` config option.
- When cookies are returned from authentication module, router wraps them in the response object.
- When a request arrives, cookies are accessible through `call.request.context.cookies` object.

2022-04-20 20:34 UTC, kon14 requested changes

2022-04-20 20:34 UTC, kon14 commented on libraries/grpc-sdk/src/helpers/RoutingUtilities.ts
> +  optional string setCookies = 3;
We [don't](https://github.com/ConduitPlatform/Conduit/issues/86) currently follow this yet, but gRPC's style guide suggests that we [use underscore_separated_names for message field names](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names).

2022-04-20 20:34 UTC, kon14 commented on modules/authentication/src/handlers/service.ts
> +      return AuthUtils.returnCookies('setCookies','Successfully authenticated',(accessToken as any).token,(refreshToken as any).token)
Cast these to `string` instead.

2022-04-20 20:34 UTC, kon14 commented on modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts
> +      return AuthUtils.returnCookies('setCookies','Successfully authenticated',(tokens.accessToken as any),(tokens.refreshToken as any))
Cast these to `string` instead.

2022-04-27 09:28 UTC, kkopanidis requested changes

2022-04-27 09:28 UTC, kkopanidis commented on libraries/grpc-sdk/src/helpers/RoutingUtilities.ts
> +message Cookie {
Missing SameSite, Domain and Path options

2022-04-27 09:28 UTC, kkopanidis commented on libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts
> +            const result = r.result ? JSON.stringify(r.result) : undefined;
Do not modify the order in which parsing and checks happen. Add an "if" statement on the top, when you create a "response" object that contains the cookie options. After that the rest of the checks should add their data in that object. For example, line 69 would do: callback(null, {...responseObject,result:r}

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts
> +      return {
message is not needed, return the userId as we regularly do and setCookies

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/facebook/facebook.ts
> +        message: ConduitString.Optional,
set/removeCookies is not a response as I've said yesterday. Remove it and also remove the message.

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/figma/figma.ts
> +        message: ConduitString.Optional,
same as my previous comment

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/github/github.ts
> +        message: ConduitString.Optional,
same as my previous comment

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/google/google.ts
> +        message: ConduitString.Optional,
same as my previous comment

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +      refreshToken: !isNil(refreshToken!) ? refreshToken!.token : undefined,
you're checking if the refreshToken is null, and at the same time you're using "refreshToken!" these are contradictory.

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/microsoft/microsoft.ts
> +        message: ConduitString.Optional,
you know what

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/phone.ts
> +        refreshToken: !isNil(refreshToken!) ? (refreshToken as RefreshToken).token : undefined,
same

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/service.ts
> +      refreshToken: !isNil(refreshToken!) ? (refreshToken as RefreshToken).token : undefined,
same

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/slack/slack.ts
> +        removeCookies: { type: [TYPE.String], required: false },
same as my previous comment

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/handlers/twitch/twitch.ts
> +        message: ConduitString.Optional,
same as my previous comment

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/interfaces/Cookie.ts
> +    httpOnly?: boolean;
add the missing options

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/routes/routes.ts
> +          removeCookies: { type: [TYPE.String], required: false },
nope

2022-04-27 09:28 UTC, kkopanidis commented on modules/authentication/src/routes/routes.ts
> +          message: ConduitString.Optional,
nope

2022-04-27 09:28 UTC, kkopanidis commented on packages/router/src/controllers/GraphQl/GraphQL.ts
> +            const cookies = JSON.parse(r.setCookies);
parsing will fail. setCookies is an object in grpc not a string

2022-04-27 15:13 UTC, kkopanidis requested changes

2022-04-27 15:13 UTC, kkopanidis commented on packages/router/src/controllers/GraphQl/utils/cookie.plugin.ts
> +            res.clearCookie(cookie.name, { domain: cookie.options.domain, path: cookie.options.path });
it needs all the options, not only domain and path

2022-04-28 08:11 UTC, kkopanidis approved these changes

2022-04-28 08:18 UTC, kon14 approved these changes

2022-04-28 09:00 UTC, merged