Third party auth providers
ConduitPlatform/Conduit pull request #14
Opened 2022-02-03 14:31 UTC by sdimitris

Made OAuth2 strategy for authenticating with third party providers.

Implemented providers:
* Facebook
* Google
* Slack
* Figma
* Github
* Microsoft
* Twitch

2022-02-08 09:49 UTC, kon14 requested changes

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/config/config.ts
> +    redirect_uri: {
Fix camelCase

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/config/config.ts
> +    redirect_uri: {
Fix camelCase

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +export abstract class AuthenticationProviderClass<T extends Payload> {
Drop "Class" suffix? AuthenticationProviderClass -> AuthenticationProvider

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/facebook.ts
> +    let payload: Payload = {
return object directly (sans assignment) or at least make payload const.

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/facebook.ts
> +    if (( isNil(context) || isEmpty(context)) && !call.request.path.startsWith('/hook'))
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/facebook.ts
> +    let { access_token } = call.request.params;
const was fine

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/google.ts
> +    super(grpcSdk,'google', url);
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/google.ts
> +  async connectWithProvider(call: ParsedRouterRequest): Promise<any> {
return type is `Promise<Payload>`

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/google.ts
> +    let googlePayload: Payload = {
return object directly (sans assignment) or at least make googlePayload const.

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/interfaces/Payload.ts
> +  email?:string;
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/interfaces/Payload.ts
> +  [field: string]:any;
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/routes/routes.ts
> +    this.facebookHandlers = new FacebookHandlers(grpcSdk,"https://graph.facebook.com/v12.0/oauth/access_token?");
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/routes/routes.ts
> +        beginAuthTwitch: this.twitchHandlers.beginAuth(this.grpcSdk,this.options).bind(this.twitchHandlers),
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/routes/routes.ts
> +          new ConduitRouteReturnDefinition('FacebookResponse', {
This is Google.

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/twitch.ts
> +    //profile_image_url = response2.data.data[0].profile_image_url;
?

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/twitch.ts
> +  async connectWithProvider(call:ParsedRouterRequest ): Promise<any> {
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/twitch.ts
> +export class TwitchHandlers extends AuthenticationProviderClass<any> {
Use T where `<T extends Payload>`

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +    let retObject: any = {
make const

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +  abstract async connectWithProvider(call: ParsedRouterRequest): Promise<any>;
Return type is `Promise<Payload>`

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +    let access_token = providerResponse.data.access_token;
make these two const. I guess the snake_case is used for compat with sth?

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +    let serverConfig = await this.grpcSdk.config.getServerConfig();
make these two const.

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +      let options = oidcSettings.getOptions;
const options and length

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +    let user: User | null | any = null;
why 'any'?

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +        [this.providerName]:  payload,
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +     //if (options.hasOwnProperty('state')) options['state'] = call.request.context.clientId;
?

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/interfaces/OIDCSettings.ts
> +    get getOptions() { return  this.options; }
spacing

2022-02-08 09:49 UTC, kon14 commented on modules/authentication/src/handlers/models/AuthenticationProviderClass.ts
> +    let payload: any;
this is { access_token, string, clientId: string }

2022-02-14 13:12 UTC, kkopanidis requested changes
fix camelCase naming in variables
add default settings for providers
remove settings interfaces since they are not needed

2022-02-14 22:19 UTC, kkopanidis approved these changes

2022-02-14 22:21 UTC, merged