Remove some any types
ConduitPlatform/Conduit pull request #160
Opened 2022-05-16 11:11 UTC by sdimitris

Some any types removed 
**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 
- [ ] Yes
- [x] No

2022-05-16 13:15 UTC, kon14 requested changes

2022-05-16 13:15 UTC, kon14 commented on packages/router/src/controllers/interfaces/Cookie.ts
> +}
Also add a new line at EOF.

2022-05-16 13:33 UTC, kon14 requested changes

2022-05-16 13:48 UTC, kon14 requested changes
Coordinate with @Michael-Vol on this.
You're both adding `ts-proto` and whatnot.

2022-05-16 13:48 UTC, kon14 commented on modules/sms/package.json
> +    "ts-proto": "^1.112.1"
Should be in dev dependencies.

2022-05-16 13:48 UTC, kon14 commented on modules/email/package.json
> +    "ts-proto": "^1.112.1"
Should be in dev dependencies.

2022-05-16 13:48 UTC, kon14 commented on modules/email/build.sh
> +rm -rf ./src/protoTypes/src/
Add new line at EOF.

2022-05-16 14:37 UTC, Michael-Vol approved these changes

2022-05-17 13:58 UTC, kkopanidis requested changes

2022-05-17 13:58 UTC, kkopanidis commented on modules/chat/package.json
> +    "build": "npm run generateTypes && rimraf dist && tsc",
move to prebuild step the generation

2022-05-17 13:58 UTC, kkopanidis commented on modules/email/package.json
> +    "build": "npm run generateTypes && rimraf dist && tsc",
same

2022-05-17 13:58 UTC, kkopanidis commented on modules/sms/package.json
> +    "build": "npm run generateTypes && rimraf dist && tsc",
same

2022-05-17 13:58 UTC, kkopanidis commented on packages/core/package.json
> +    "build": "npm run generateTypes && rimraf dist && tsc",
same

2022-05-18 10:44 UTC, kkopanidis approved these changes

2022-05-18 11:17 UTC, kon14 requested changes
Please add new lines at EOF, otherwise legit.

2022-05-18 11:17 UTC, kon14 commented on packages/commons/build.sh
> +rm -f ./src/core.proto
Add a new line at EOF

2022-05-18 13:23 UTC, kon14 approved these changes

2022-05-18 13:32 UTC, merged