fix(database): array type not extracted properly
ConduitPlatform/Conduit pull request #182
Opened 2022-06-01 11:03 UTC by Michael-Vol

**What kind of change does this PR introduce?** 
This PR fixes an issue where the extracted array type in Mongoose is "Array".
- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch

2022-06-01 11:06 UTC, kon14 requested changes

2022-06-01 11:06 UTC, kon14 commented on modules/database/src/adapters/mongoose-adapter/index.ts
> +          crudOperations: {},
Shouldn't this be `crudOperations: { create: { enabled: false, authenticated: false }, read: ..., update: ..., delete: ... }`?

2022-06-01 11:06 UTC, kon14 commented on modules/database/src/introspection/mongoose/utils.ts
> +    while(nestedField.hasOwnProperty('types'))
Spacing

2022-06-02 14:07 UTC, kon14 requested changes

2022-06-02 14:07 UTC, kon14 commented on modules/database/src/adapters/mongoose-adapter/index.ts
> +          crudOperations: {
Where Sequelize bruh

2022-06-02 14:11 UTC, kon14 approved these changes

2022-06-02 21:45 UTC, kkopanidis approved these changes

2022-06-02 21:45 UTC, merged