feat: added notes and alias options for creating client ids
ConduitPlatform/Conduit pull request #196
Opened 2022-06-08 13:39 UTC by Michael-Vol

**What kind of change does this PR introduce?** 
This PR adds support for adding optional alias and notes fields when creating client ids in security. It addresses the issue when there are multiple client ids and cannot be distinguished one from another solely from the id.
Solves #192.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2022-06-08 14:59 UTC, kon14 requested changes

2022-06-08 14:59 UTC, kon14 commented on packages/security/src/admin/routes/UpdateSecurityClient.route.ts
> +        throw new ConduitError('INVALID_PARAMS', 400, 'Client id not found');
Rephrase this as "Security client not found" or something.

2022-06-08 15:10 UTC, kon14 approved these changes

2022-06-08 16:03 UTC, kkopanidis requested changes

2022-06-08 16:03 UTC, kkopanidis commented on packages/security/src/admin/routes/UpdateSecurityClient.route.ts
> +        platform: ConduitString.Optional,
platform is not an acceptable argument. As we've discussed the user cannot change the platform

2022-06-08 16:03 UTC, kkopanidis commented on packages/security/src/admin/routes/UpdateSecurityClient.route.ts
> +      clientSecret: ConduitString.Required,
client secret should not be returned after client creation

2022-06-09 08:26 UTC, kkopanidis approved these changes

2022-06-09 08:26 UTC, merged