Database admin routes register without router
ConduitPlatform/Conduit pull request #233
Opened 2022-07-13 14:54 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

2022-07-13 14:56 UTC, kkopanidis requested changes

2022-07-13 15:22 UTC, kon14 requested changes

2022-07-13 15:22 UTC, kon14 commented on modules/database/src/Database.ts
> +      const extOwner = call.metadata!.get('module-name')![0] as string as string;
Not sure why that double cast was previously there in the first place, but a single one should suffice.

2022-07-13 15:22 UTC, kon14 commented on modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts
> +      .then((r: any) => {
Use `ICustomEndpoint` for this type.

2022-07-13 15:22 UTC, kon14 commented on modules/database/src/controllers/cms/schema.controller.ts
> +    if (this.router === null) {
We probably shouldn't warn for these. Just return from the function.
Same for rest of these checks.

2022-07-14 09:16 UTC, kon14 requested changes

2022-07-14 09:16 UTC, kon14 commented on modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts
> +      .then((r: any) => {
My bad, we don't actually need the response at all.

2022-07-14 09:26 UTC, kkopanidis approved these changes

2022-07-14 09:41 UTC, kon14 approved these changes

2022-07-14 09:41 UTC, merged