feat(authentication): implement change email
ConduitPlatform/Conduit pull request #255
Opened 2022-07-21 11:09 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**Other information:**
To test implementation use hardcoded (this.sendEmail = true) as currently a **bugfix is on the way**  
Verification is now done through hooks, after bugfix logically an email will be sent to user

2022-07-21 12:03 UTC, kon14 requested changes

2022-07-21 12:03 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +                      If 2FA is enabled then a message will be returned asking for token input.`,
Remove 2FA reference from description.

2022-07-21 12:04 UTC, kon14 commented
This is going to have to be rebased against #257 (or vice-versa).

2022-07-22 08:44 UTC, kon14 approved these changes

2022-07-23 14:32 UTC, kkopanidis requested changes

2022-07-23 14:32 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +          .sendEmail('EmailVerification', {
Use the new template name you created, not the old one

2022-07-23 14:32 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +    const dupEmailUser = await User.getInstance().findOne({ email: newEmail });
make this check after the check of line 590, before checking password validation. In  general you should try and keep a parameters validation in the same place and not in various locations throughout the code.

2022-07-25 11:01 UTC, kkopanidis approved these changes

2022-07-25 11:01 UTC, merged