chore(hermes): move swagger admins paths from core tag to admin tag
ConduitPlatform/Conduit pull request #259
Opened 2022-07-22 14:38 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other (chore)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

2022-07-22 15:00 UTC, kon14 requested changes

2022-07-22 15:00 UTC, kon14 commented on libraries/hermes/src/Rest/Swagger.ts
> +    let prefix = serviceName.substring(0, serviceName.indexOf('/'));
Make this a constant.

2022-07-22 15:03 UTC, kon14 commented on libraries/hermes/src/Rest/Swagger.ts
> +    let prefix = serviceName.substring(0, serviceName.indexOf('/'));
Actually no, the previous line is what prefix should be initialized as.
Service name should be declared early, but assigned an initial value in the if / else blocks below.

2022-07-22 16:06 UTC, kon14 approved these changes

2022-07-23 14:26 UTC, kkopanidis approved these changes

2022-07-23 14:26 UTC, merged