feat(authentication): resend verification email
ConduitPlatform/Conduit pull request #264
Opened 2022-07-25 13:01 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**Other information:**
Resend verification email when creating a new user

2022-07-25 13:41 UTC, kkopanidis requested changes

2022-07-25 13:41 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +      .sendEmail('ChangeEmailVerification', {
you're using the change email verification instead of the email verification template

2022-07-25 13:44 UTC, kon14 requested changes

2022-07-25 13:44 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +        path: '/local/resend-verification',
Make this `/local/new/send-verification` as it's not clear what sort of verification send this URI performs.
Update handler name to reflect this.

This should also only get registered whenever `this.sendVerificationEmail` is true.

2022-07-25 13:44 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +    if (!this.sendVerificationEmail) return 'Configuration not set to send email';
We shouldn't be registering this route in that case.

2022-07-25 13:44 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +    const verificationToken: Token | null = await Token.getInstance().findOne({
We should probably recreate these instead, replacing any existing ones of that type for target user.
What if we let these expire down the line?
What if token creation failed for whatever reason, in which case we're stuck with a non-verifiable user.

2022-07-25 13:44 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +    return 'Verification email resent';
Make this `Verification code sent`.
We shouldn't treat this as a resend route/function.

2022-07-26 10:47 UTC, kon14 requested changes

2022-07-26 10:47 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +    if (this.sendVerificationEmail) {
This should only register whenever `this.sendVerificationEmail` is true.
Move this into the relevant block above.

2022-07-26 10:47 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +    if (user.isVerified) return 'User is already verified';
This should throw an error instead.

2022-07-26 14:28 UTC, kon14 requested changes

2022-07-26 14:28 UTC, kon14 commented on modules/authentication/src/handlers/local.ts
> +      throw new GrpcError(status.FAILED_PRECONDITION, 'User already exists');
`User is already verified` was fine. I only requested that the return be changed to a throw.

2022-07-26 15:02 UTC, kon14 approved these changes

2022-07-26 15:03 UTC, kkopanidis approved these changes

2022-07-26 15:03 UTC, merged