fix(admin): auth middleware body query check
ConduitPlatform/Conduit pull request #281
Opened 2022-08-10 09:15 UTC by kon14

Fixes query param check failing for REST requests containing a `query` body param.

**What kind of change does this PR introduce?** 

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

2022-08-10 09:16 UTC, Michael-Vol approved these changes

2022-08-18 15:19 UTC, kkopanidis requested changes

2022-08-18 15:19 UTC, kkopanidis commented on packages/admin/src/middleware/Auth.middleware.ts
> +    req.body.query.startsWith('{\n')
These checks require the existence of a special character "\n" to work. This doesn't seem stable at all, we don't care about general content just the existence of a specific query. This check needs to be changed to reflect that in a more concrete manner

2022-08-23 08:23 UTC, kkopanidis approved these changes

2022-08-23 08:23 UTC, merged