Prometheus Metrics Support
ConduitPlatform/Conduit pull request #282
Opened 2022-08-11 15:14 UTC by Michael-Vol

**What kind of change does this PR introduce?** 
This PR adds support for metrics collection. Each module collects a variety of default metrics (e.g. request latencies, gRPC errors, admin/client requests etc.). In addition to these defaults every module also records and collects some custom metrics regarding its function. For instance the authentication module records any login requests that have been sent. Each module exposes a Prometheus compatible endpoint ```/metrics```, providing support for Prometheus scraping. To enable metrics, each module must be provided with a ```METRICS_PORT``` env key for the Express server port.
Metrics collection is totally optional and can be enabled to some or all of the modules.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

2022-08-22 09:08 UTC, kon14 requested changes

2022-08-22 09:08 UTC, kon14 commented on libraries/grpc-sdk/src/classes/ManagedModule.ts
> +   * types and configuration by using the sdk's ConduitMetrics?.
Remove the optional chaining `?` reference

2022-08-22 09:08 UTC, kon14 commented on modules/database/src/metrics/index.ts
> +    //TODO: create global query error handler to track this
Comment this out until implemented?

2022-08-22 09:08 UTC, kon14 commented on modules/storage/src/storage-provider/providers/google/index.ts
> +      )[0].size; //TODO: check if this is the correct way to get the file size
We need to test this.

2022-08-22 09:08 UTC, kon14 commented on modules/storage/src/storage-provider/providers/aliyun/index.ts
> +    // ConduitGrpcSdk.Metrics?.decrement('storage_size_bytes_total', fileSize); TODO: get file size from oss client
We need to figure out how to get this from aliyun.

2022-08-23 08:35 UTC, kon14 commented on modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
> +        ?.increment(parsedQuery['$inc'], { where: { _id: id } })
There's another one of these in the same file.

2022-08-23 08:42 UTC, kon14 requested changes

2022-08-23 08:42 UTC, kon14 commented on modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
> -        ?.increment(parsedQuery['$inc'], { where: { _id: id } })
There's another instance of this in the same file.

2022-08-23 08:42 UTC, kon14 commented on modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
> +const incrementDBQueries = () =>
Make this camel case.

2022-08-24 13:18 UTC, kon14 approved these changes

2022-08-25 11:22 UTC, kkopanidis approved these changes

2022-08-25 11:22 UTC, merged