feat(authentication): add qr code library for 2fa authentication
ConduitPlatform/Conduit pull request #283
Opened 2022-08-22 09:11 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

2022-08-22 13:55 UTC, kkopanidis requested changes
Changes discussed on call.

2022-08-22 14:18 UTC, kon14 requested changes

2022-08-23 08:55 UTC, kon14 requested changes

2022-08-23 08:55 UTC, kon14 commented on modules/authentication/src/TwoFactorAuth.ts
> +  ): Promise<{ userId: String; accessToken: String; refreshToken: String }> {
Use `string` as a data type.

2022-08-23 08:55 UTC, kon14 commented on modules/authentication/src/TwoFactorAuth.ts
> +  UnparsedRouterResponse,
Remove unused import.

2022-08-23 09:27 UTC, kon14 approved these changes

2022-08-23 09:30 UTC, kkopanidis approved these changes

2022-08-23 09:30 UTC, merged