refactor(database): admin custom endpoints methods rework for code factor
ConduitPlatform/Conduit pull request #296
Opened 2022-08-30 11:11 UTC by ChrisPdgn

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

2022-08-30 11:23 UTC, kon14 requested changes

2022-08-30 11:23 UTC, kon14 commented on modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
> +  async findSchema(
Make this private.

2022-08-30 11:53 UTC, kon14 reviewed
CodeFactor still complains over `operationValidation()`'s complexity.
I personally think it's clean enough for humans, but if we really wish to make this bot-rating-friendly, maybe the following would work:

```
const invalidArray = !Array.isArray(assignments) || assignments.length === 0;
if (invalidArray && [OperationsEnum.POST, OperationsEnum.PUT, OperationsEnum.PATCH].includes(operation))
```

2022-08-31 13:08 UTC, kon14 requested changes

2022-08-31 13:24 UTC, kon14 approved these changes

2022-08-31 14:43 UTC, kkopanidis approved these changes

2022-08-31 14:44 UTC, merged