feat: add node-2fa library
ConduitPlatform/Conduit pull request #347
Opened 2022-09-23 15:16 UTC by ChrisPdgn

The creation of this new library is meant to help with occurring problems and reduce external dependencies.
Subsequently, this library will be used from an upcoming central 2fa handler, in order to simplify 2fa process. 
So any duplicate code and other redundant stuff will be dealt with soon.

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature

2022-09-23 15:47 UTC, kkopanidis requested changes

2022-09-23 15:47 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +      if (verification.delta === -1)
do not provide extra codes. If delta is anything else besides 0, provide a 400 error (wrong params) and a message that the code is not correct

2022-09-23 15:47 UTC, kkopanidis commented on modules/authentication/src/handlers/local.ts
> +    if (verification.delta === -1)
do not provide extra codes. If delta is anything else besides 0, provide a 400 error (wrong params) and a message that the code is not correct

2022-09-23 15:47 UTC, kkopanidis commented on libraries/node-2fa/package.json
> +{
Add here the author details from the original repo. We need to make sure we give credit to the author

2022-09-26 15:39 UTC, kon14 approved these changes

2022-09-27 09:00 UTC, merged