Improved redis support
ConduitPlatform/Conduit pull request #435
Opened 2022-11-18 14:22 UTC by SotiriaSte

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2022-11-18 14:29 UTC, kkopanidis requested changes

2022-11-18 14:29 UTC, kkopanidis commented on libraries/grpc-sdk/package.json
> +    "@types/fs-extra": "^9.0.13",
types are dev dependencies. ioredis,lodash etc have been added in prod dependencies due to other issues. So please move.

2022-11-21 09:07 UTC, ChrisPdgn commented on libraries/grpc-sdk/src/index.ts
> +      let redisConfig = process.env.REDIS_CONFIG;
Define as const

2022-11-21 09:45 UTC, ChrisPdgn approved these changes

2022-11-22 17:48 UTC, kkopanidis approved these changes

2022-11-22 17:49 UTC, merged