feat(database,grpc-sdk): raw query support
ConduitPlatform/Conduit pull request #445
Opened 2022-11-23 13:23 UTC by ChrisPdgn

This PR adds a new rpc for raw query execution.
A raw query can be like this:
```javascript
rawQuery = {
      rawMongoQuery?: {
        query: 'insertOne',
        queryBody: {
          _id: 'example',
          username: 'example'
        }
      } ,
      rawSqlQuery?: {
        query: 'SELECT * FROM "cnd_User"',
        options?: {
          nest: true
        }
      }
    }
```

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature

2022-11-23 13:36 UTC, kon14 requested changes

2022-11-23 13:36 UTC, kon14 commented on modules/database/src/database.proto
> +message rawQuery {
Protobuff message names should be PascalCase.
`RawMongoQuery` and `RawSqlQuery` definitions can be nested inside `RawQuery`.

2022-11-23 13:36 UTC, kon14 commented on modules/database/src/database.proto
> +message CombinedRawQueryRequest {
Simplify this to `RawQueryRequest`.

2022-11-24 10:12 UTC, kon14 requested changes

2022-11-24 11:58 UTC, kkopanidis commented on modules/database/src/database.proto
> +        message MongoQuery {
oneOf not enum

2022-11-24 13:05 UTC, kon14 approved these changes

2022-11-24 15:18 UTC, kkopanidis approved these changes

2022-11-24 15:25 UTC, merged