Functions module
ConduitPlatform/Conduit pull request #474
Opened 2022-12-22 16:15 UTC by SotiriaSte

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2023-01-05 13:58 UTC, kkopanidis requested changes

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/metrics/index.ts
> +export default {
add another metric to measure function execution times for each function. The function name or id will be defined via labels on the metric

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/admin/index.ts
> +        description: 'Get function Definitions for specific function',
these are logs/executions not definitions

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/controllers/function.controller.ts
> +  private crudRoutes: {
we don't have crud and custom routes here.

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/controllers/function.controller.ts
> +  addRoutes(
this is not needed here, add the routes in the object in a proper manner.

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/controllers/utils.ts
> +      import: ['lodash'],
make sure that lodash is in package.json, and also add here and in package.json "axios".

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/controllers/utils.ts
> +    await addSchemaDefinitions(name, duration, true, undefined, logs);
function executions are not schema definitions

2023-01-05 13:58 UTC, kkopanidis commented on modules/functions/src/controllers/utils.ts
> +    const functionData = functionInSandbox(grpcSdk, call.request, callback);
the function  ends after line 59 has been executed, but you are measuring duration before.

2023-01-05 16:08 UTC, kkopanidis requested changes

2023-01-05 16:08 UTC, kkopanidis commented on modules/functions/src/admin/index.ts
> +    return Functions.getInstance().create(query);
How is the new function going to be published? You only create the model, you do not refresh the routes

2023-01-05 17:37 UTC, kkopanidis approved these changes

2023-01-09 11:01 UTC, ChrisPdgn approved these changes

2023-01-09 11:23 UTC, sdimitris reviewed
It is my belief that the "/functions/upload" route's body should be evaluated due to the fact that if the input is incorrect, FunctionsExecutions will not be created.

Let me know if I'm wrong. @kon14  @ChrisPdgn @SotiriaSte  @kkopanidis

2023-01-10 10:39 UTC, merged