Codefactor issues
ConduitPlatform/Conduit pull request #523
Opened 2023-02-16 14:10 UTC by SotiriaSte

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2023-02-16 14:54 UTC, kon14 requested changes

2023-02-16 14:54 UTC, kon14 commented on modules/authentication/src/interfaces/IFetchMembersParams.ts
> +  skip?: any;
skip is numeric

2023-02-17 10:21 UTC, kkopanidis approved these changes

2023-02-17 10:42 UTC, kon14 approved these changes

2023-02-17 13:39 UTC, merged