feat: sql data types
ConduitPlatform/Conduit pull request #547
Opened 2023-03-02 13:17 UTC by SotiriaSte

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [X] No

**The PR fulfills these requirements:**

- [X] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2023-03-02 15:18 UTC, kkopanidis requested changes
The SQLDataType should be in a new sqlType field an not extra options for the existing type field.

2023-03-03 09:49 UTC, kon14 reviewed
While not necessarily breaking anything as unsupported types would simply fall back to the base type's default representation, shouldn't this come with a validation layer?

2023-03-03 11:25 UTC, kkopanidis requested changes

2023-03-03 11:25 UTC, kkopanidis commented on libraries/grpc-sdk/src/interfaces/Model.ts
> +export enum SQLDataType {
remove BLOB, JSONB, UUID and use TIME/DATETIME/TIMESTAMP values in extractType

2023-03-03 15:13 UTC, kkopanidis approved these changes

2023-03-03 15:13 UTC, merged