feat(storage): add file uploads by url instead of base64
ConduitPlatform/Conduit pull request #550
Opened 2023-03-08 17:29 UTC by kkopanidis

fix(storage): add consistent expiry of signed urls

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature 

**Other information:**

2023-03-08 17:30 UTC, kkopanidis commented
Missing to add updateFile by url as well

2023-03-09 13:22 UTC, kon14 requested changes

2023-03-09 13:22 UTC, kon14 commented on modules/storage/src/providers/azure/index.ts
> +import { SIGNED_URL_EXPIRY, SIGNED_URL_EXPIRY_DATE } from '../../constants/expiry';
Unused import

2023-03-21 13:17 UTC, kon14 approved these changes

2023-03-21 13:17 UTC, ChrisPdgn approved these changes

2023-03-21 13:22 UTC, merged