feat(admin,router,hermes,grpc-sdk,core): middleware patch support
ConduitPlatform/Conduit pull request #614
Opened 2023-05-04 13:08 UTC by ChrisPdgn

This PR introduces the feature of patching the middleware array of a grpc route. This applies for admin and app routes. Middleware order can be changed freely, but removal is allowed only to the module that registered the middleware. 

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [x] Yes
- [ ] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature

2023-05-04 14:55 UTC, kon14 requested changes

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/Router.ts
> +    this.grpcSdk.createModuleClient('router', process.env.SERVICE_IP!);
What would this accomplish? The Router's own `grpc-sdk` shouldn't be communicating with itself through gRPC.

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/Router.ts
> +  async patchMiddleware(
Maybe rename this to `patchRouteMiddlewares` or sth that would convey we're actually affecting the route's middlewares.

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/Router.ts
> +      moduleUrl = await this.grpcSdk.config.getModuleUrlByName('router').then(r => r.url);
Add a comment clarifying this is about administrators modifying client API middlewares.

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/admin/index.ts
> +          path: ConduitString.Required,
This is REST-oriented.
Not saying we could/should change this, but we should probably document it a bit.

As is, this should include the module name in the path.
Does this work for hooks? What's the path for a hook given the order swap going on.

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/admin/index.ts
> +        path: '/router/patch-middleware',
Either `'/router/patch-middleware'` -> `'/router/patch-middlewares'` or update the getter route. Pick one as long as it's consistent in the external APIs.
Also update descriptions.

2023-05-04 14:55 UTC, kon14 commented on modules/router/src/admin/router.ts
> +  async getRouteMiddlewares(call: ParsedRouterRequest): Promise<UnparsedRouterResponse> {
Do these work with hooks?

2023-05-05 08:50 UTC, ChrisPdgn commented on modules/router/src/admin/router.ts
> +  async getRouteMiddlewares(call: ParsedRouterRequest): Promise<UnparsedRouterResponse> {
After testing it, yes they do

2023-05-07 22:20 UTC, kon14 requested changes
Just a couple leftovers.

2023-05-07 22:20 UTC, kon14 commented on libraries/hermes/src/Router.ts
> +    routeMiddleware: string[],
`routeMiddlewares` / `patchMiddlewares`

2023-05-07 22:20 UTC, kon14 commented on libraries/hermes/src/index.ts
> +    routeMiddleware: string[],
`routeMiddlewares` / `patchMiddlewares`

2023-05-08 08:44 UTC, kon14 approved these changes

2023-05-08 09:17 UTC, merged