Routing Improvements
ConduitPlatform/Conduit pull request #62
Opened 2022-03-03 20:36 UTC by kkopanidis

The target of this PR is to make routing declaration more consistent and clear older code and methods of declaring routes.
Goals:
- Consistent declaration and features between Admin and Client routers
- Remove custom code from Admin/Client router grpc client files
- Create any and all utility functions required to add enough sugar in route declaration

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ x Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:
Existing applications should use the new functions introduced and remove the older functions. Applications using the 0.11 sdk version should not be affected.

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2022-03-20 19:44 UTC, kkopanidis commented
I'm still thinking that maybe I need to also make the admin changes in this PR, so that admin and client router registrations are consistent but I'll leave it to the reviewers to decide if the PR is already too big

2022-03-21 10:32 UTC, kon14 commented on modules/forms/src/controllers/forms.controller.ts
> +  private async loadExistingForms() {
Why do we need a private copy of refreshRoutes?

2022-03-21 11:07 UTC, kon14 requested changes
Can we keep a consistent naming for RoutingManager object members?
Some classes use _routingController while others use _routingManager.

Besides that, I think we can get rid of `loadExistingForms()` in `Forms.FormsController` and call the public `refreshRoutes` in its constructor just like we do everywhere else.

Beyond that, looks LGTM 🎉

2022-03-21 11:10 UTC, kon14 commented
> I'm still thinking that maybe I need to also make the admin changes in this PR, so that admin and client router registrations are consistent but I'll leave it to the reviewers to decide if the PR is already too big

Lets address that in a followup PR. Prettier already produces huge diffs.

2022-03-21 12:18 UTC, kon14 approved these changes

2022-03-21 13:01 UTC, sdimitris approved these changes

2022-03-21 13:03 UTC, Michael-Vol approved these changes

2022-03-21 13:52 UTC, merged