feat(sms):add aws,clickSend,messageBird providers
ConduitPlatform/Conduit pull request #633
Opened 2023-06-07 11:42 UTC by laertis99

**What kind of change does this PR introduce?** 

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** 

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's description  (e.g. `fix #xxx`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature 

**Other information:**

2023-06-17 15:57 UTC, kkopanidis requested changes

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/package.json
> +    "@types/otp-generator": "^4.0.0",
@types/ packages should be in dev dependencies

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/package.json
> +    "bluebird": "^3.7.2",
bluebird has no place here

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/package.json
> +    "@types/bluebird": "^3.5.38",
remove bluebird

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/src/Sms.ts
> +        case 'aws':
rename to aws-sns and the provider to AwsSnsProvider. AWS contains more than one messaging solutions and just adding "SNS" might confuse the users

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/src/providers/aws.ts
> +    const otp = generate(6, {
please move the generate OTP function to a utils file, so that the implementation is centralized

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/src/providers/aws.ts
> +      return Promise.resolve(result.MessageId);
just return the results. Promise.resolve is redundant

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/src/providers/aws.ts
> +      return Promise.resolve(result.MessageId);
Apply this to all relevant blocks of code in the PR

2023-06-17 15:57 UTC, kkopanidis commented on modules/sms/src/providers/messageBird.ts
> +    await this.client.messages.create(
you need to wrap this in a promise as you do in the other 2 functions of messagebird since they are not async

2023-06-19 11:08 UTC, laertis99 commented on modules/sms/package.json
> +    "bluebird": "^3.7.2",
used by clickSend

2023-06-19 11:09 UTC, laertis99 commented on modules/sms/package.json
> +    "@types/bluebird": "^3.5.38",
used by clickSend

2023-06-19 12:45 UTC, ChrisPdgn requested changes

2023-06-19 12:45 UTC, ChrisPdgn commented on modules/sms/src/config/config.ts
> +  AwsSns: {
rename to 'awsSns'

2023-06-19 12:45 UTC, ChrisPdgn commented on modules/sms/src/providers/awsSns.ts
> +    return Promise.resolve(phoneNumber);
remove this promise resolve

2023-06-20 07:46 UTC, ChrisPdgn approved these changes

2023-06-20 09:24 UTC, kon14 approved these changes

2023-06-20 12:06 UTC, kkopanidis approved these changes

2023-06-20 12:06 UTC, merged