fix(core): socket pushes not working
ConduitPlatform/Conduit pull request #82
Opened 2022-03-19 20:18 UTC by kkopanidis

The io object seems weird in its behaviour,
but the changes should allow for connected
sockets to receive the data correctly

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

2022-03-19 20:18 UTC, kkopanidis commented
Proper testing is needed, I'm still facing network issues.

2022-03-25 15:23 UTC, kon14 commented on modules/chat/src/routes/routes.ts
> +    const { roomId, message } = call.request.params;
This should be `[ roomId, message ]`. Socket params are an array.

2022-03-25 15:23 UTC, kon14 commented on modules/chat/src/routes/routes.ts
> +    const { roomId } = call.request.params;
Same ^

2022-03-25 15:25 UTC, kon14 requested changes
ParsedSocketRequest's `call.request.params` are an array.
Object destructuring will produce `undefined`.

2022-03-25 15:28 UTC, kkopanidis commented
@kon14 slow down, I'm looking at these right now, I only resolved conflicts previously. Even without the resolution it wouldn't work there are multiple typing issues.

2022-03-28 09:21 UTC, kon14 approved these changes

2022-03-28 12:44 UTC, merged